/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsAhoCorasick = AhoCorasick
export class AhoCorasick {
  isMatch(input: string): boolean
  static withPatterns(patterns: Array<string>): JsAhoCorasick
}
export type JsZipReader = ZipReader
export class ZipReader {
  viaBuffer(buffer: Buffer): void
  static withDestinationPath(path: string): JsZipReader
}
